////
  Copyright 2021 The Bank of New York Mellon.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////
= Topics

Below is a list of topics on the Spring Framework path:

. link:00_Introduction.adoc[Introduction]

. link:01_InversionOfControl.adoc[Inversion of Control]

. link:02_DependencyInjection.adoc[Dependency Injection]

. link:02_SpringBasicsSummary.adoc[IoC and DI - Summary]

. link:03_Testing.adoc[Testing with Spring]

. link:04_PersistenceWithJDBC.adoc[Persistence with JDBC]

. link:05_PersistenceWithHibernate.adoc[Persistence with Hibernate]

. link:06_PersistenceWithJPA.adoc[Persistence with JPA]

. link:07_PersistenceWithSpringDataJPA.adoc[Persistence with Spring Data JPA]